### ISSUE TITLE
Feature request: writing eml files

### ISSUE THREAD

**Issue by gaa-cifasis** [peti/hsemail#3]
Hi,

I was wondering if the support for writing eml files is planned (a suitable Show or Binary instance should be enough).

Thanks!

**Comment by peti** [comment]
I have no knowledge of EML files, and I don't have access to any of the (Windows-based?) tools that create them either. From what I read on the Internet, an EML file is basically an RFC822-formatted text file, so reading/writing them should be no big effort given the available infrastructure, but personally I don't see myself implementing such a feature since I can't even test it.

**Comment by gaa-cifasis** [comment]
I think that pretty printing to RFC822 will be enough to write EML files in fact. It can be useful to automatize the testing of hsmail using QuickCheck [like this](https://lstephen.wordpress.com/2007/07/29/parsec-parser-testing-with-quickcheck/) (in fact, we can easily provide the Arbitrary instances automatically if you want). 

In any case, i will try to find some time to implement it ..

**Comment by peti** [comment]
Closing because of apparent inactivity.
